/*
 * DialogoNuevaPartida.java
 *
 * Created on April 9, 2008, 4:50 PM
 */
package eps.catan.gui;

import eps.Util;
import eps.multij.Jugador;
import java.net.MalformedURLException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author  mfreire
 */
public class DialogoNuevaPartida extends JDialog implements PartidaRemota {

    private PanelJugador[] paneles = new PanelJugador[4];
    int nJugadores = 0;
    private boolean aceptado = false;
    private ArrayList<Jugador> jugadoresRemotos = new ArrayList<Jugador>();

    public PanelJugador[] getDatosJugadores() {
        PanelJugador[] jr = new PanelJugador[nJugadores];
        for (int i = 0; i < nJugadores; i++) {
            jr[i] = paneles[i];
        }
        return jr;
    }

    public boolean isAceptado() {
        return aceptado;
    }

    /** Creates new form DialogoNuevaPartida */
    public DialogoNuevaPartida(java.awt.Frame parent, String titulo, int n, boolean force) {
        super(parent, titulo, true);
        initComponents();

        String[] listaNombres = {
            "Alberto", "Alejandro", "Alfonso", "Almudena", "Alvaro", "Ana", "Andres",
            "Angel", "Antonio", "Ascension", "Carlos", "Carmen", "Conrado", "Daniel",
            "David", "Diana", "Diego", "Doroteo", "Eduardo", "Elena", "Elias", "Elisa",
            "Eloy", "Enrique", "Estanislao", "Esther", "Estrella", "Eugenio",
            "Fabiano", "Fabrizio", "Fernando", "Francisco", "Gabriel", "German",
            "Gonzalo", "Guillermo", "Gustavo", "Ignacio", "Ivan", "Jaime", "Javier",
            "Jesus", "Joaquin", "Jordi", "Jorge", "Jose", "Juan", "Juana", "Julia",
            "Kostadin", "Kurosh", "Leila", "Luis", "Manuel", "Maria", "Mariano",
            "Marina", "Mick", "Miguel", "Miren", "Moises", "Montserrat", "Narciso",
            "Nicolas", "Pablo", "Pedro", "Pilar", "Rafael", "Roberto", "Rodolfo", "Rosa",
            "Ruth", "Saul", "Sergio", "Silvia", "Susana", "Vicente", "Victor", "Xavier"
        };
        List<String> permutacion = Arrays.asList(listaNombres);
        Util.baraja(permutacion);
        for (int i = 0; i < paneles.length; i++) {
            paneles[i] = new PanelJugador(i, permutacion.get(i));
        }
        setSize(400, 300);
        jcbNumJugadores.setSelectedItem("" + n);
        if (force) {
            jcbNumJugadores.setEnabled(false);
        }
    }

    /**
     * Muestra 'n' jugadores
     * @param n numero de jugadores a mostrar
     */
    private void muestraJugadores(int n) {
        jpCentro.removeAll();
        for (int i = 0; i < n; i++) {
            jpCentro.add(paneles[i]);
        }
        jpCentro.revalidate();
    }

    public Jugador getRemoto(int i) {
        return jugadoresRemotos.get(i);
    }

    public boolean entrarEnPartida(Jugador j) throws RemoteException {
        int remotos = 0;
        boolean ok = false;

        for (int i = 0; i < nJugadores; i++) {
            if (paneles[i].isRemoto()) {
                remotos++;
                if (jugadoresRemotos.size() < remotos) {
                    paneles[i].setNombre(j.getNombre());
                    jugadoresRemotos.add(j);
                    System.err.println("Admitido jugador " + j.getNombre() + " en pos " + i);
                    ok = true;
                    break;
                }
            }
        }

        if (remotos == jugadoresRemotos.size()) {
            aceptado = true;
            dispose();
        }

        return ok;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCentro = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcbNumJugadores = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jbCancelar = new javax.swing.JButton();
        jbAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jpCentro.setLayout(new javax.swing.BoxLayout(jpCentro, javax.swing.BoxLayout.Y_AXIS));
        getContentPane().add(jpCentro, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Num. Jugadores");
        jPanel2.add(jLabel1);

        jcbNumJugadores.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4" }));
        jcbNumJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbNumJugadoresActionPerformed(evt);
            }
        });
        jPanel2.add(jcbNumJugadores);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });
        jPanel3.add(jbCancelar);

        jbAceptar.setText("Aceptar");
        jbAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAceptarActionPerformed(evt);
            }
        });
        jPanel3.add(jbAceptar);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void jcbNumJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbNumJugadoresActionPerformed
        String si = jcbNumJugadores.getSelectedItem().toString().trim();
        nJugadores = Integer.parseInt(si);
        muestraJugadores(nJugadores);
}//GEN-LAST:event_jcbNumJugadoresActionPerformed

    private void jbAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAceptarActionPerformed
        aceptado = true;
        int remotos = 0;
        for (int i = 0; i < nJugadores; i++) {
            if (paneles[i].isRemoto()) {
                remotos++;
            }
        }
        if (remotos > 0) {
            for (int i = 0; i < nJugadores; i++) {
                paneles[i].setEnabled(false);
            }
            jcbNumJugadores.setEnabled(false);
            jbAceptar.setEnabled(false);
            String nombrePartida = JOptionPane.showInputDialog("" +
                    "<html>Introduce un <b>nombre</b> para la partida en red, <br>" +
                    "la partida comenzará automáticamente una vez que se añadan <br>" +
                    "tus colegas (usando '//ip-de-esta-maquina/nombre-partida').</html>");
            if (nombrePartida != null && nombrePartida.length() > 0) {
                try {
                    java.rmi.server.UnicastRemoteObject.exportObject(this);
                    java.rmi.Naming.rebind("//localhost/" + nombrePartida, this);
                    aceptado = true;
                    return;
                } catch (RemoteException e) {
                    System.out.println("RE registrandose como partida remota");
                    e.printStackTrace();
                } catch (MalformedURLException e) {
                    System.out.println("MalFormedURLException en rebind de setJugadorEnEspera(...).");
                }
            }
        }
        aceptado = true;
        dispose();
    }//GEN-LAST:event_jbAceptarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        aceptado = false;
        dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JComboBox jcbNumJugadores;
    private javax.swing.JPanel jpCentro;
    // End of variables declaration//GEN-END:variables
}
