/*
 * PanelJugador.java
 *
 * Created on April 9, 2008, 4:50 PM
 */

package eps.catan.gui;

import java.awt.Component;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author  mfreire
 */
public class PanelJugador extends javax.swing.JPanel {
    
    /** Creates new form PanelJugador */
    public PanelJugador(int i, String nombre) {
        initComponents();
        jlNombre.setText("Jugador "+i);
        setNombre(nombre);
        jcbTipo.setModel(new DefaultComboBoxModel(new String[] {
            "Humano", "Automatico", "Remoto"})
        );
    }
    
    public void setEnabled(boolean enabled) {
        super.setEnabled(enabled);
        for (Component c : getComponents()) c.setEnabled(enabled);
    }
    
    public void setNombre(String s) {
        jtfNombre.setText(s);
    }
    
    public String getNombre() {
        return jtfNombre.getText();
    }
    
    public boolean isAutomatico() {
        return jcbTipo.getSelectedIndex() == 1;
    }
    
    public boolean isRemoto() {
        return jcbTipo.getSelectedIndex() == 2;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jlNombre = new javax.swing.JLabel();
        jcbTipo = new javax.swing.JComboBox();
        jtfNombre = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        jlNombre.setText("Jugador ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(jlNombre, gridBagConstraints);

        jcbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4" }));
        jcbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTipoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(jcbTipo, gridBagConstraints);

        jtfNombre.setText("nombre-del-jugador");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(jtfNombre, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jcbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTipoActionPerformed
        // TODO add your handling code here:
        jtfNombre.setEnabled( ! isRemoto());
    }//GEN-LAST:event_jcbTipoActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jcbTipo;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JTextField jtfNombre;
    // End of variables declaration//GEN-END:variables
    
}
